name: CI Worflow

on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
          cache-dependency-path: 'typescript/yarn.lock'
      - run: |
            cd typescript;
            yarn install;