name: CI Worflow

on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
          cache-dependency-path: 'typescript/yarn.lock'
      - run: |
            cd typescript;
            yarn install;