name: CI Worflow

on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
          cache-dependency-path: 'typescript/yarn.lock'
      - run: |
            cd typescript;
            yarn install;