name: CI Worflow

on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: .tool-versions
          cache: yarn
          cache-dependency-path: 'typescript/yarn.lock'
      - run: |
            cd typescript;
            yarn install;