name: CI Worflow

on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: .tool-versions
          cache: yarn
          cache-dependency-path: 'typescript/yarn.lock'
      - run: |
            cd typescript;
            yarn install;